#!/usr/bin/env python3
"""
setup_imports.py — RDIP Ontology Local Import Setup
====================================================
Downloads all ontologies that rdip.ttl depends on and places them in an
`imports/` folder at the project root. Also generates a catalog-v001.xml
file in each directory that contains a .ttl ontology file, so Protégé
resolves remote IRIs locally without any network calls.
"""

import os
import urllib.request
import urllib.error
import textwrap
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# CONFIGURATION
# Each entry:  (canonical IRI used in owl:imports,  local filename,  list of URLs to try in order)
# ─────────────────────────────────────────────────────────────────────────────

IMPORTS = [
    (
        "http://vivoweb.org/ontology/core",
        "vivo-core.owl",
        [
            # Try the GitHub raw file first — most reliable
            "https://raw.githubusercontent.com/vivo-ontologies/vivo-ontology/refs/heads/master/vivo.owl",
            # Fallback: direct VIVO site
            "http://vivoweb.org/ontology/core",
        ],
    ),
    (
        "http://purl.org/ontology/bibo/",
        "bibo.owl",
        [
            "http://purl.org/ontology/bibo/bibo.owl",
            "https://raw.githubusercontent.com/structureddynamics/Bibliographic-Ontology-BIBO/master/bibo.owl",
        ],
    ),
    (
        "http://www.w3.org/ns/dcat#",
        "dcat.ttl",
        [
            "https://www.w3.org/ns/dcat2.ttl",
            "https://www.w3.org/ns/dcat.ttl",
        ],
    ),
    (
        "http://www.w3.org/ns/prov-o#",
        "prov-o.ttl",
        [
            "https://www.w3.org/ns/prov-o.ttl",
            "https://www.w3.org/ns/prov.ttl",
        ],
    ),
    (
        "http://purl.org/spar/cito/",
        "cito.ttl",
        [
            "https://sparontologies.github.io/cito/current/cito.ttl",
            "http://purl.org/spar/cito/cito.ttl",
        ],
    ),
]

# ─────────────────────────────────────────────────────────────────────────────
# STUB TEMPLATES
# If all download attempts fail, a minimal valid OWL stub is written so that
# Protégé can still open the ontology without crashing. The stub declares
# the ontology IRI and a comment explaining it is a placeholder.
# ─────────────────────────────────────────────────────────────────────────────

def make_stub(iri: str, filename: str) -> str:
    return textwrap.dedent(f"""\
        @prefix owl:   <http://www.w3.org/2002/07/owl#> .
        @prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
        @prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
        @prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .

        # ──────────────────────────────────────────────────────────────────────
        # STUB — {filename}
        # This is a placeholder generated by setup_imports.py because the
        # ontology at <{iri}> could not be downloaded.
        # Replace this file with the real ontology when connectivity allows.
        # ──────────────────────────────────────────────────────────────────────

        <{iri}>
            a owl:Ontology ;
            rdfs:comment "Stub placeholder for {iri}. Replace with the real ontology file."@en .
    """)

# ─────────────────────────────────────────────────────────────────────────────
# CATALOG TEMPLATE
# Protégé reads catalog-v001.xml from the same directory as the opened .ttl.
# The `uri` attribute is the canonical IRI; the `name` attribute is the
# relative path to the local file.
# ─────────────────────────────────────────────────────────────────────────────

def make_catalog(entries: list[tuple[str, str]], imports_relative_path: str) -> str:
    """
    entries: list of (canonical_iri, local_filename)
    imports_relative_path: relative path from the catalog's directory to imports/
                           e.g. '../imports' or '../../imports'
    """
    uri_lines = "\n".join(
        f'    <uri name="{iri}" uri="{imports_relative_path}/{filename}"/>'
        for iri, filename in entries
    )
    return textwrap.dedent(f"""\
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <catalog prefer="public" xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
        {uri_lines}
        </catalog>
    """)

# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def download(url: str, dest: Path, timeout: int = 15) -> bool:
    """Attempt to download url to dest. Returns True on success."""
    try:
        print(f"Trying {url}")
        req = urllib.request.Request(url, headers={"Accept": "text/turtle, application/rdf+xml, */*"})
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            content = resp.read()
        dest.write_bytes(content)
        print(f"Saved ({len(content):,} bytes)")
        return True
    except urllib.error.URLError as e:
        print(f"Failed: {e.reason}")
        return False
    except Exception as e:
        print(f"Error: {e}")
        return False


def write_catalog(path: Path, content: str):
    path.write_text(content, encoding="utf-8")
    print(f"Wrote {path}")

# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

def main():
    # Locate project root (script should be run from there)
    project_root = Path.cwd()
    imports_dir  = project_root / "imports"
    imports_dir.mkdir(exist_ok=True)
    print(f"Project root : {project_root}")
    print(f"Imports dir  : {imports_dir}\n")

    # ── Step 1: Download (or stub) each dependency ──────────────────────────
    catalog_entries = []  # (iri, filename) for catalog generation

    for iri, filename, urls in IMPORTS:
        dest = imports_dir / filename
        print(f"{filename}  [{iri}]")

        if dest.exists():
            print(f"Already exists — skipping download")
            catalog_entries.append((iri, filename))
            continue

        success = False
        for url in urls:
            if download(url, dest):
                success = True
                break

        if not success:
            print(f"All URLs failed — writing stub")
            dest.write_text(make_stub(iri, filename), encoding="utf-8")

        catalog_entries.append((iri, filename))
        print()

    # ── Step 2: Write catalog files ─────────────────────────────────────────
    # Catalog locations and their relative path back to imports/
    catalog_locations = [
        (project_root / "core",              "../imports"),
        (project_root / "versions" / "v1.0", "../../imports"),
        (project_root / "versions" / "v2.0", "../../imports"),
    ]

    print("\nWriting catalog-v001.xml files …\n")
    for folder, rel_imports in catalog_locations:
        if folder.exists():
            catalog_path = folder / "catalog-v001.xml"
            write_catalog(catalog_path, make_catalog(catalog_entries, rel_imports))
        else:
            print(f"Folder not found, skipping: {folder}")

    # ── Step 3: Summary ─────────────────────────────────────────────────────
    print("\n" + "─" * 60)
    print("Setup complete!\n")
    print("Files in imports/:")
    for f in sorted(imports_dir.iterdir()):
        size = f.stat().st_size
        tag = "[STUB]" if size < 500 else "[OK]  "
        print(f"  {tag} {f.name}  ({size:,} bytes)")

    print("""
        Next steps:
        1. Open Protégé.
        2. Go to File → Open → select core/rdip.ttl  (or any versioned .ttl).
        3. Protégé will read catalog-v001.xml automatically and resolve all
            imports locally — no internet required.
        4. If any file is marked [STUB], replace it with the real ontology
            when you have connectivity and re-run this script (delete the stub
            first so it re-downloads).
        """
    )


if __name__ == "__main__":
    main()
