name: Deploy Docs

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Setup Pages
        uses: actions/configure-pages

      - name: Upload WIDOCO docs
        uses: actions/upload-pages-artifact
        with:
          path: ./core/docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages
